# version 1.0
name: CI/CD - Upgrade Chart and Deploy 
on:
  release:
    types: [created]

jobs:
  deploy:
    name: deploy to totoro
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-totoro

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get repository name
        id: repo_name
        run: echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)"

      - name: Upgrade package chart
        run: |
          helm package --app-version ${{ github.ref_name }} --version ${{ github.event.release.name }} ./.chart

      - name: Upgrade Helm chart
        run: |
          APP_NAME="${{ steps.repo_name.outputs.name }}"
          PACKAGE_FILE=$(ls -r *.tgz | head -n 1)
          helm upgrade --install $APP_NAME $PACKAGE_FILE